= Podman Desktop Tutorial

You can access the HTML version of this tutorial here: https://redhat-scholars.github.io/podman-desktop-tutorial/[window="_blank"]

## Building the guide in a container

In order to test and develop on your local machine, you can use a specially built container with Podman or Docker as follows, run this from the root folder:

[source,sh]
----
podman run --rm --name antora -v $PWD:/antora -p 8080:8080 -i -t ghcr.io/juliaaano/antora-viewer
----

Live-reload is not supported.

## Building the HTML locally

In the root of your git repository, run:

```
bin/build-site.sh
```

And then open your `gh-pages/index.html` file:

```
open gh-pages/index.html
```

## Iterative local development

You can develop the tutorial docs locally using a rapid iterative cycle.

First, install the `yarn` dependencies:

[source,bash]
----
yarn install
----

And now start `gulp`. It will create the website and open your browser connected with `browser-sync`. Everytime it detects a change, it will automatically refresh your browser page.

[source,bash]
----
gulp
----

You can clean the local cache using:

[source,bash]
----
gulp clean
----
